Add conditional lambda deploy

diff --git a/.github/workflows/reusable-workflow.yml b/.github/workflows/reusable-workflow.yml
--- a/.github/workflows/reusable-workflow.yml
+++ b/.github/workflows/reusable-workflow.yml
@@ -202,31 +202,6 @@ jobs:
               ["${{ needs.deploy_ecr.outputs.FUNCTION_NAME_PROCESS_FRAMES }}"]="$image_repo_process_frames"
           )
 
-          max_retries=5
-          retry_count=0
-          retry_delay=20
-          while true; do
-            repository_failed=0
-            for function_name in "${!function_images[@]}"; do
-                repo_name="${function_images[$function_name]}"
-                aws ecr describe-repositories --repository-names "$repo_name" > /dev/null 2>&1
-                if [ $? -ne 0 ]; then
-                    echo "Repository $repo_name does not exist. Retrying..."
-                    repository_failed=$((repository_failed + 1))
-                fi
-            done
-            if [ $repository_failed -eq 0 ]; then
-                echo "All repositories exist. Proceeding with Docker build."
-                break
-            fi
-            retry_count=$((retry_count + 1))
-            retry_delay=$((retry_delay * 2))
-            if [ $retry_count -ge $max_retries ]; then
-                echo "Failed to describe repository after $max_retries attempts. Exiting."
-                exit 1
-            fi
-          done
-
           cd lambdas
           for function_name in "${!function_images[@]}"; do
               repo_name="${function_images[$function_name]}"
@@ -333,6 +308,31 @@ jobs:
       - name: Terraform Apply on Dev
         if: github.ref == 'refs/heads/dev' && github.event_name == 'push' && inputs.stage == 'dev'
         run: |
+          max_retries=5
+          retry_count=0
+          retry_delay=30
+          while true; do
+            repository_failed=0
+            for function_name in "${!function_images[@]}"; do
+                repo_name="${function_images[$function_name]}"
+                pushed_tag=$(aws ecr list-images --repository-name "$repo_name" --query "imageIds[?imageTag=='latest'].imageTag" --output text)
+                if [ "$pushed_tag" != "latest" ]; then
+                    echo "Repository $repo_name does not have the latest tag. Retrying..."
+                    repository_failed=$((repository_failed + 1))
+                fi
+            done
+            if [ $repository_failed -eq 0 ]; then
+                echo "All repositories has images. Proceeding with lambda deployment."
+                break
+            fi
+            retry_count=$((retry_count + 1))
+            retry_delay=$((retry_delay * 2))
+            if [ $retry_count -ge $max_retries ]; then
+                echo "Failed to get images after $max_retries attempts. Exiting."
+                exit 1
+            fi
+          done
+
           ecr_repo_base_uri=$(cat base_repo_uri.txt)
           terraform apply \
             -var="stage=${{ inputs.stage }}" \
